export const BLOCK_ACTION_TYPES = {
    SET_NUM_ROWS: "SET_NUM_ROWS",
    SET_NUM_COLS: "SET_NUM_COLS",
    SET_START: "SET_START",
    SET_END: "SET_END",
    ADD_OBSTACLE: "ADD_OBSTACLE",
    SET_VISITED: "SET_VISITED",
    SET_TO_VISIT: "SET_TO_VISIT",
    SET_TRUE_PATH: "SET_TRUE_PATH",
    CLEAR_OBSTACLES: "CLEAR_OBSTACLES",
    CLEAR_PATH: "CLEAR_PATH",
    CLEAR_ALL: "CLEAR_ALL",
    RANDOMIZE_OBSTACLES: "RANDOMIZE_OBSTACLES"
}
